// SPDX-FileCopyrightText: 2025 Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache-2.0

import { Transaction as SequelizeTransaction } from 'sequelize';

export { SequelizeTransaction };
export * as sequelize from './src/db/sequelize/index.js';
export * from './src/interfaces/index.js';
export * from 'sequelize-typescript';
export type { PaginatedParams } from './src/db/sequelize/index.js';
export {
  Authorization,
  Boot,
  ChangeConfiguration,
  ChargingNeeds,
  ChargingProfile,
  ChargingSchedule,
  ChargingStation,
  ChargingStationSequence,
  Component,
  Connector,
  DefaultSequelizeInstance,
  Evse,
  Location,
  MeterValue,
  OCPPMessage,
  Tariff,
  StartTransaction,
  StopTransaction,
  Transaction,
  Reservation,
  Subscription,
  EvseType,
  Variable,
  VariableAttribute,
  VariableCharacteristics,
  VariableStatus,
  Certificate,
  InstalledCertificate,
  InstallCertificateAttempt,
  DeleteCertificateAttempt,
  CountryNameEnumType,
  TransactionEvent,
  LocalListAuthorization,
  LocalListVersion,
  SendLocalList,
  ServerNetworkProfile,
  SetNetworkProfile,
  StatusNotification,
  ChargingStationSecurityInfo,
  ChargingStationNetworkProfile,
  Tenant,
  TenantPartner,
  AsyncJobStatus,
  AsyncJobStatusDTO,
  AsyncJobRequest,
  SignatureAlgorithmEnumType,
  SequelizeAuthorizationRepository,
  SequelizeBootRepository,
  SequelizeComponentRepository,
  SequelizeOCPPMessageRepository,
  SequelizeCertificateRepository,
  SequelizeInstalledCertificateRepository,
  SequelizeInstallCertificateAttemptRepository,
  SequelizeDeleteCertificateAttemptRepository,
  SequelizeChangeConfigurationRepository,
  SequelizeChargingProfileRepository,
  SequelizeChargingStationNetworkProfileRepository,
  SequelizeChargingStationSecurityInfoRepository,
  SequelizeDeviceModelRepository,
  SequelizeLocationRepository,
  SequelizeMessageInfoRepository,
  SequelizeRepository,
  SequelizeReservationRepository,
  SequelizeSecurityEventRepository,
  SequelizeSubscriptionRepository,
  SequelizeTariffRepository,
  SequelizeTransactionEventRepository,
  SequelizeVariableMonitoringRepository,
  SequelizeChargingStationSequenceRepository,
  SequelizeTenantRepository,
  SequelizeAsyncJobStatusRepository,
  SequelizeServerNetworkProfileRepository,
  SequelizeSetNetworkProfileRepository,
  SequelizeLocalAuthListRepository,
  OCPP2_0_1_Mapper,
  OCPP1_6_Mapper,
  OCPP2_1_Mapper,
} from './src/db/sequelize/index.js'; // TODO ensure all needed modules are properly exported
export type { CompositeScheduleInput } from './src/mappers/2.0.1/charging-profile-mapper.js';
export type { TariffData } from './src/models/tariff/tariffs.js';
export { RepositoryStore } from './src/repositories/sequelize/repository-store.js';
export {
  DefaultDrizzleInstance,
  DrizzleAuthorizationRepository,
  DrizzleBootRepository,
  DrizzleCertificateRepository,
  DrizzleDeleteCertificateAttemptRepository,
  DrizzleInstallCertificateAttemptRepository,
  DrizzleInstalledCertificateRepository,
  DrizzleLocationRepository,
  DrizzleMessageInfoRepository,
  DrizzleSecurityEventRepository,
  DrizzleServerNetworkProfileRepository,
  DrizzleSubscriptionRepository,
  DrizzleTariffRepository,
  DrizzleTenantRepository,
  DrizzleVariableAttributeRepository,
} from './src/db/drizzle/index.js';
