// Copyright (c) 2023 S44, LLC
// Copyright Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache 2.0

import { OCPP2_0_1, OCPP2_0_1_Namespace } from '@citrineos/base';
import {
  BelongsTo,
  BelongsToMany,
  Column,
  DataType,
  ForeignKey,
  Table,
} from 'sequelize-typescript';
import { Evse } from './Evse';
import { Variable } from './Variable';
import { ComponentVariable } from './ComponentVariable';
import { BaseModelWithTenant } from '../BaseModelWithTenant';

@Table({
  indexes: [
    {
      unique: true,
      fields: ['name'],
      where: {
        instance: null,
      },
    },
  ],
})
export class Component extends BaseModelWithTenant implements OCPP2_0_1.ComponentType {
  static readonly MODEL_NAME: string = OCPP2_0_1_Namespace.ComponentType;

  /**
   * Fields
   */

  @Column({
    type: DataType.STRING,
    unique: 'name_instance',
  })
  declare name: string;

  @Column({
    type: DataType.STRING,
    unique: 'name_instance',
  })
  declare instance?: string | null;

  /**
   * Relations
   */

  @BelongsTo(() => Evse)
  declare evse?: OCPP2_0_1.EVSEType;

  @ForeignKey(() => Evse)
  @Column(DataType.INTEGER)
  declare evseDatabaseId?: number | null;

  @BelongsToMany(() => Variable, () => ComponentVariable)
  declare variables?: OCPP2_0_1.VariableType[];

  declare customData?: OCPP2_0_1.CustomDataType | null;

  // Declare the association methods, to be automatically generated by Sequelize at runtime
  public addVariable!: (variable: Variable) => Promise<void>;
  public getVariables!: () => Promise<Variable[]>;
}
