// Copyright Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache 2.0

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { ChangeAvailabilityResponseStatus } from '../enums';
import { OcppResponse } from '../../../..';

export interface ChangeAvailabilityResponse extends OcppResponse {
  status: ChangeAvailabilityResponseStatus;
}
