// Copyright Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache 2.0

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {
  GetCompositeScheduleResponseStatus,
  GetCompositeScheduleResponseChargingRateUnit,
} from '../enums';
import { OcppResponse } from '../../../..';

export interface GetCompositeScheduleResponse extends OcppResponse {
  status: GetCompositeScheduleResponseStatus;
  connectorId?: number | null;
  scheduleStart?: string | null;
  chargingSchedule?: {
    duration?: number | null;
    startSchedule?: string | null;
    chargingRateUnit: GetCompositeScheduleResponseChargingRateUnit;
    chargingSchedulePeriod: {
      startPeriod: number;
      limit: number;
      numberPhases?: number | null;
    }[];
    minChargingRate?: number | null;
  };
}
