// SPDX-FileCopyrightText: 2025 Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache-2.0

import { Transaction as SequelizeTransaction } from 'sequelize';

export { SequelizeTransaction };
export * as sequelize from './layers/sequelize/index.js';
export * from './interfaces/index.js';
export * from 'sequelize-typescript';
export type { PaginatedParams } from './layers/sequelize/index.js';
export {
  Authorization,
  Boot,
  ChangeConfiguration,
  ChargingNeeds,
  ChargingProfile,
  ChargingSchedule,
  ChargingStation,
  ChargingStationSequence,
  Component,
  Connector,
  DefaultSequelizeInstance,
  Evse,
  Location,
  MeterValue,
  OCPPMessage,
  Tariff,
  StartTransaction,
  StopTransaction,
  Transaction,
  Reservation,
  Subscription,
  EvseType,
  Variable,
  VariableAttribute,
  VariableCharacteristics,
  VariableStatus,
  Certificate,
  InstalledCertificate,
  CountryNameEnumType,
  TransactionEvent,
  LocalListAuthorization,
  LocalListVersion,
  SendLocalList,
  ServerNetworkProfile,
  SetNetworkProfile,
  StatusNotification,
  ChargingStationSecurityInfo,
  ChargingStationNetworkProfile,
  Tenant,
  TenantPartner,
  AsyncJobStatus,
  AsyncJobStatusDTO,
  AsyncJobRequest,
  AsyncJobName,
  AsyncJobAction,
  SignatureAlgorithmEnumType,
  SequelizeAuthorizationRepository,
  SequelizeBootRepository,
  SequelizeOCPPMessageRepository,
  SequelizeCertificateRepository,
  SequelizeInstalledCertificateRepository,
  SequelizeChangeConfigurationRepository,
  SequelizeChargingProfileRepository,
  SequelizeChargingStationSecurityInfoRepository,
  SequelizeDeviceModelRepository,
  SequelizeLocationRepository,
  SequelizeMessageInfoRepository,
  SequelizeRepository,
  SequelizeReservationRepository,
  SequelizeSecurityEventRepository,
  SequelizeSubscriptionRepository,
  SequelizeTariffRepository,
  SequelizeTransactionEventRepository,
  SequelizeVariableMonitoringRepository,
  SequelizeChargingStationSequenceRepository,
  SequelizeTenantRepository,
  SequelizeAsyncJobStatusRepository,
  SequelizeServerNetworkProfileRepository,
  OCPP2_0_1_Mapper,
  OCPP1_6_Mapper,
} from './layers/sequelize/index.js'; // TODO ensure all needed modules are properly exported
export { RepositoryStore } from './layers/sequelize/repository/RepositoryStore.js';
export { CryptoUtils } from './util/CryptoUtils.js';
