// SPDX-FileCopyrightText: 2025 Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache-2.0

/**
 * Boots a Postgres testcontainer, runs all legacy `core/migrations/*.ts`
 * sequelize migrations against it, then `pg_dump --schema-only` dumps the
 * resulting schema to `nestjs/migrations/0000_legacy_bootstrap.sql`.
 *
 * Why a bootstrap dump rather than per-migration ports:
 *
 *   - The legacy migration set includes one (`add-charging-station-pk-id`)
 *     that walks `information_schema` at runtime to discover FKs by
 *     column. Translating it to static SQL or a single PL/pgSQL DO
 *     block is involved.
 *   - Several other migrations use JS for-loops over hard-coded table
 *     lists; auto-translation works but produces noisy output.
 *
 * The dump captures the *exact* final schema state, so nestjs runs
 * byte-identical migrations to legacy by construction. Future legacy
 * migrations land as additional `.sql` files (use
 * `port-legacy-migrations.ts` on the new file only).
 *
 * Run:  cd nestjs && npx ts-node -r tsconfig-paths/register --project tsconfig.json scripts/dump-legacy-schema.ts
 */

import { execSync, spawnSync } from 'child_process';
import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { GenericContainer, type StartedTestContainer, Wait } from 'testcontainers';

const MONOREPO_ROOT = join(__dirname, '..', '..');
const OUTPUT_PATH = join(__dirname, '..', 'migrations', '0000_legacy_bootstrap.sql');
const JOURNAL_PATH = join(__dirname, '..', 'migrations', 'meta', '_journal.json');

async function bootPostgres(): Promise<{ container: StartedTestContainer; port: number }> {
  const container = await new GenericContainer('postgis/postgis:16-3.5')
    .withEnvironment({
      POSTGRES_USER: 'postgres',
      POSTGRES_PASSWORD: 'postgres',
      POSTGRES_DB: 'postgres',
    })
    .withExposedPorts(5432)
    .withWaitStrategy(Wait.forLogMessage('ready to accept connections', 2))
    .withStartupTimeout(120_000)
    .start();
  return { container, port: container.getMappedPort(5432) };
}

async function main(): Promise<void> {
  console.log('▶ Booting Postgres testcontainer…');
  const { container, port } = await bootPostgres();
  try {
    console.log('▶ Running legacy sequelize migrations…');
    execSync('npm run migrate', {
      cwd: MONOREPO_ROOT,
      stdio: 'inherit',
      env: {
        ...process.env,
        BOOTSTRAP_CITRINEOS_DATABASE_HOST: 'localhost',
        BOOTSTRAP_CITRINEOS_DATABASE_PORT: String(port),
        BOOTSTRAP_CITRINEOS_DATABASE_USERNAME: 'postgres',
        BOOTSTRAP_CITRINEOS_DATABASE_PASSWORD: 'postgres',
        BOOTSTRAP_CITRINEOS_DATABASE_NAME: 'postgres',
        BOOTSTRAP_CITRINEOS_DATABASE_DIALECT: 'postgres',
      },
    });

    console.log('▶ Dumping schema via pg_dump…');
    // Use the pg_dump bundled with the testcontainer to avoid depending on
    // a host-installed copy. Skip postgis catalog tables (we exclude them
    // from drift checks too).
    const dump = spawnSync(
      'docker',
      [
        'exec',
        container.getId(),
        'pg_dump',
        '--schema-only',
        '--no-owner',
        '--no-privileges',
        '--no-comments',
        '--exclude-schema=tiger',
        '--exclude-schema=tiger_data',
        '--exclude-schema=topology',
        '--exclude-table=public.spatial_ref_sys',
        '--exclude-table=public.SequelizeMeta',
        '-U',
        'postgres',
        '-d',
        'postgres',
      ],
      { encoding: 'utf8', maxBuffer: 50 * 1024 * 1024 },
    );
    if (dump.status !== 0) {
      throw new Error(`pg_dump failed (${dump.status}): ${dump.stderr}`);
    }

    const header = `-- Bootstrap schema for nestjs.
-- Generated by scripts/dump-legacy-schema.ts from running every
-- migration in core/migrations/ against a fresh Postgres. Drizzle-kit
-- applies this via npm run migrate; the resulting schema is byte-for-byte
-- identical to legacy by construction.
--
-- Future legacy migrations should be ported individually as additional
-- nestjs/migrations/NNNN_<name>.sql files (see scripts/port-legacy-migrations.ts).
-- Do NOT regenerate this bootstrap once additional per-migration files
-- exist — that would erase the audit trail and re-apply already-applied
-- statements.

`;

    writeFileSync(OUTPUT_PATH, header + dump.stdout);

    // Drizzle journal entry — single bootstrap migration.
    mkdirSync(join(__dirname, '..', 'migrations', 'meta'), { recursive: true });
    writeFileSync(
      JOURNAL_PATH,
      JSON.stringify(
        {
          version: '7',
          dialect: 'postgresql',
          entries: [
            {
              idx: 0,
              version: '7',
              when: Date.now(),
              tag: '0000_legacy_bootstrap',
              breakpoints: false,
            },
          ],
        },
        null,
        2,
      ),
    );

    console.log(`\n✅ Wrote ${OUTPUT_PATH}`);
    console.log(`   ${dump.stdout.split('\n').length} lines from pg_dump`);
  } finally {
    await container.stop();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
