export enum HttpHeader {
  ContentType = 'Content-Type',
  ContentLength = 'Content-Length',
  Accept = 'Accept',
  Authorization = 'Authorization',
  CacheControl = 'Cache-Control',
  UserAgent = 'User-Agent',
  AcceptEncoding = 'Accept-Encoding',
  AcceptLanguage = 'Accept-Language',
  Connection = 'Connection',
  Host = 'Host',
  Referer = 'Referer',
  Origin = 'Origin',
  AccessControlAllowOrigin = 'Access-Control-Allow-Origin',
  ETag = 'ETag',
  IfNoneMatch = 'If-None-Match',
}
