export enum CommandType {
  CANCEL_RESERVATION = 'CANCEL_RESERVATION',
  RESERVE_NOW = 'RESERVE_NOW',
  START_SESSION = 'START_SESSION',
  STOP_SESSION = 'STOP_SESSION',
  UNLOCK_CONNECTOR = 'UNLOCK_CONNECTOR',
}
