// SPDX-FileCopyrightText: 2025 Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache-2.0

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { BootReasonEnumType } from '../enums/index.js';
import type { OcppRequest } from '../../../../index.js';

export interface BootNotificationRequest extends OcppRequest {
  chargingStation: ChargingStationType;
  reason: BootReasonEnumType;
  customData?: CustomDataType | null;
}
/**
 * The physical system where an Electrical Vehicle (EV) can be charged.
 *
 */
export interface ChargingStationType {
  /**
   * Vendor-specific device identifier.
   *
   */
  serialNumber?: string | null;
  /**
   * Defines the model of the device.
   *
   */
  model: string;
  modem?: ModemType | null;
  /**
   * Identifies the vendor (not necessarily in a unique manner).
   *
   */
  vendorName: string;
  /**
   * This contains the firmware version of the Charging Station.
   *
   *
   */
  firmwareVersion?: string | null;
  customData?: CustomDataType | null;
}
/**
 * Defines parameters required for initiating and maintaining wireless communication with other devices.
 *
 */
export interface ModemType {
  /**
   * This contains the ICCID of the modem’s SIM card.
   *
   */
  iccid?: string | null;
  /**
   * This contains the IMSI of the modem’s SIM card.
   *
   */
  imsi?: string | null;
  customData?: CustomDataType | null;
}
/**
 * This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
 */
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
