// SPDX-FileCopyrightText: 2025 Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache-2.0

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { TariffClearStatusEnumType } from '../enums/index.js';
import type { OcppResponse } from '../../../../index.js';

export interface ClearTariffsResponse extends OcppResponse {
  /**
   * @minItems 1
   */
  clearTariffsResult: [ClearTariffsResultType, ...ClearTariffsResultType[]];
  customData?: CustomDataType | null;
}
export interface ClearTariffsResultType {
  statusInfo?: StatusInfoType | null;
  /**
   * Id of tariff for which _status_ is reported. If no tariffs were found, then this field is absent, and _status_ will be `NoTariff`.
   *
   */
  tariffId?: string | null;
  status: TariffClearStatusEnumType;
  customData?: CustomDataType | null;
}
/**
 * Element providing more information about the status.
 *
 */
export interface StatusInfoType {
  /**
   * A predefined code for the reason why the status is returned in this response. The string is case-insensitive.
   *
   */
  reasonCode: string;
  /**
   * Additional text to provide detailed information.
   *
   */
  additionalInfo?: string | null;
  customData?: CustomDataType | null;
}
/**
 * This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
 */
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
