// SPDX-FileCopyrightText: 2025 Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache-2.0

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { DERControlEnumType } from '../enums/index.js';
import type { OcppRequest } from '../../../../index.js';

export interface ClearDERControlRequest extends OcppRequest {
  /**
   * True: clearing default DER controls. False: clearing scheduled controls.
   *
   *
   */
  isDefault: boolean;
  controlType?: DERControlEnumType | null;
  /**
   * Id of control setting to clear. When omitted all settings for _controlType_ are cleared.
   *
   *
   */
  controlId?: string | null;
  customData?: CustomDataType | null;
}
/**
 * This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
 */
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
