// SPDX-FileCopyrightText: 2025 Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache-2.0

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Iso15118EVCertificateStatusEnumType } from '../enums/index.js';
import type { OcppResponse } from '../../../../index.js';

export interface Get15118EVCertificateResponse extends OcppResponse {
  status: Iso15118EVCertificateStatusEnumType;
  statusInfo?: StatusInfoType | null;
  /**
   * *(2/1)* Raw CertificateInstallationRes response for the EV, Base64 encoded. +
   * Extended to support ISO 15118-20 certificates. The minimum supported length is 17000. If a longer _exiResponse_ is supported, then the supported length must be communicated in variable OCPPCommCtrlr.FieldLength[ "Get15118EVCertificateResponse.exiResponse" ].
   *
   *
   */
  exiResponse: string;
  /**
   * *(2.1)* Number of contracts that can be retrieved with additional requests.
   *
   */
  remainingContracts?: number | null;
  customData?: CustomDataType | null;
}
/**
 * Element providing more information about the status.
 *
 */
export interface StatusInfoType {
  /**
   * A predefined code for the reason why the status is returned in this response. The string is case-insensitive.
   *
   */
  reasonCode: string;
  /**
   * Additional text to provide detailed information.
   *
   */
  additionalInfo?: string | null;
  customData?: CustomDataType | null;
}
/**
 * This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
 */
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
