// SPDX-FileCopyrightText: 2025 Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache-2.0

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { CertificateStatusSourceEnumType, HashAlgorithmEnumType } from '../enums/index.js';
import type { OcppRequest } from '../../../../index.js';

export interface GetCertificateChainStatusRequest extends OcppRequest {
  /**
   * @minItems 1
   * @maxItems 4
   */
  certificateStatusRequests:
    | [CertificateStatusRequestInfoType]
    | [CertificateStatusRequestInfoType, CertificateStatusRequestInfoType]
    | [
        CertificateStatusRequestInfoType,
        CertificateStatusRequestInfoType,
        CertificateStatusRequestInfoType,
      ]
    | [
        CertificateStatusRequestInfoType,
        CertificateStatusRequestInfoType,
        CertificateStatusRequestInfoType,
        CertificateStatusRequestInfoType,
      ];
  customData?: CustomDataType | null;
}
/**
 * Data necessary to request the revocation status of a certificate.
 *
 */
export interface CertificateStatusRequestInfoType {
  certificateHashData: CertificateHashDataType;
  source: CertificateStatusSourceEnumType;
  /**
   * URL(s) of _source_.
   *
   *
   * @minItems 1
   * @maxItems 5
   */
  urls:
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string];
  customData?: CustomDataType | null;
}
export interface CertificateHashDataType {
  hashAlgorithm: HashAlgorithmEnumType;
  /**
   * The hash of the issuer’s distinguished
   * name (DN), that must be calculated over the DER
   * encoding of the issuer’s name field in the certificate
   * being checked.
   *
   *
   */
  issuerNameHash: string;
  /**
   * The hash of the DER encoded public key:
   * the value (excluding tag and length) of the subject
   * public key field in the issuer’s certificate.
   *
   */
  issuerKeyHash: string;
  /**
   * The string representation of the
   * hexadecimal value of the serial number without the
   * prefix "0x" and without leading zeroes.
   *
   */
  serialNumber: string;
  customData?: CustomDataType | null;
}
/**
 * This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
 */
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
