// SPDX-FileCopyrightText: 2025 Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache-2.0

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { DERControlEnumType } from '../enums/index.js';
import type { OcppRequest } from '../../../../index.js';

export interface GetDERControlRequest extends OcppRequest {
  /**
   * RequestId to be used in ReportDERControlRequest.
   *
   */
  requestId: number;
  /**
   * True: get a default DER control. False: get a scheduled control.
   *
   *
   */
  isDefault?: boolean | null;
  controlType?: DERControlEnumType | null;
  /**
   * Id of setting to get. When omitted all settings for _controlType_ are retrieved.
   *
   *
   */
  controlId?: string | null;
  customData?: CustomDataType | null;
}
/**
 * This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
 */
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
