// SPDX-FileCopyrightText: 2025 Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache-2.0

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type { OcppResponse } from '../../../../index.js';

export interface NotifySettlementResponse extends OcppResponse {
  /**
   * The receipt URL if receipt generated by CSMS. The Charging Station can QR encode it and show it to the EV Driver.
   *
   *
   */
  receiptUrl?: string | null;
  /**
   * The receipt id if the receipt is generated by CSMS.
   *
   *
   */
  receiptId?: string | null;
  customData?: CustomDataType | null;
}
/**
 * This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
 */
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
