// SPDX-FileCopyrightText: 2025 Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache-2.0

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {} from '../../../../index.js';

export interface NotifyPeriodicEventStream {
  /**
   * @minItems 1
   */
  data: [StreamDataElementType, ...StreamDataElementType[]];
  /**
   * Id of stream.
   *
   */
  id: number;
  /**
   * Number of data elements still pending to be sent.
   *
   */
  pending: number;
  /**
   * Base timestamp to add to time offset of values.
   *
   */
  basetime: string;
  customData?: CustomDataType | null;
}
export interface StreamDataElementType {
  /**
   * Offset relative to _basetime_ of this message. _basetime_ + _t_ is timestamp of recorded value.
   *
   */
  t: number;
  v: string;
  customData?: CustomDataType | null;
}
/**
 * This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
 */
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
