// SPDX-FileCopyrightText: 2025 Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache-2.0

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type { OcppRequest } from '../../../../index.js';

export interface NotifyDERStartStopRequest extends OcppRequest {
  /**
   * Id of the started or stopped DER control.
   * Corresponds to the _controlId_ of the SetDERControlRequest.
   *
   *
   */
  controlId: string;
  /**
   * True if DER control has started. False if it has ended.
   *
   *
   */
  started: boolean;
  /**
   * Time of start or end of event.
   *
   *
   */
  timestamp: string;
  /**
   * List of controlIds that are superseded as a result of this control starting.
   *
   *
   *
   * @minItems 1
   * @maxItems 24
   */
  supersededIds?: [string, ...string[]] | null;
  customData?: CustomDataType | null;
}
/**
 * This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
 */
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
