// SPDX-FileCopyrightText: 2025 Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache-2.0

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { PublishFirmwareStatusEnumType } from '../enums/index.js';
import type { OcppRequest } from '../../../../index.js';

export interface PublishFirmwareStatusNotificationRequest extends OcppRequest {
  status: PublishFirmwareStatusEnumType;
  /**
   * Required if status is Published. Can be multiple URI’s, if the Local Controller supports e.g. HTTP, HTTPS, and FTP.
   *
   *
   * @minItems 1
   */
  location?: [string, ...string[]] | null;
  /**
   * The request id that was
   * provided in the
   * PublishFirmwareRequest which
   * triggered this action.
   *
   */
  requestId?: number | null;
  statusInfo?: StatusInfoType | null;
  customData?: CustomDataType | null;
}
/**
 * Element providing more information about the status.
 *
 */
export interface StatusInfoType {
  /**
   * A predefined code for the reason why the status is returned in this response. The string is case-insensitive.
   *
   */
  reasonCode: string;
  /**
   * Additional text to provide detailed information.
   *
   */
  additionalInfo?: string | null;
  customData?: CustomDataType | null;
}
/**
 * This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
 */
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
