// SPDX-FileCopyrightText: 2025 Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache-2.0

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { GenericStatusEnumType } from '../enums/index.js';
import type { OcppResponse } from '../../../../index.js';

export interface VatNumberValidationResponse extends OcppResponse {
  company?: AddressType | null;
  statusInfo?: StatusInfoType | null;
  /**
   * VAT number that was requested.
   *
   *
   */
  vatNumber: string;
  /**
   * EVSE id for which check was requested.
   *
   *
   */
  evseId?: number | null;
  status: GenericStatusEnumType;
  customData?: CustomDataType | null;
}
/**
 * *(2.1)* A generic address format.
 *
 */
export interface AddressType {
  /**
   * Name of person/company
   *
   */
  name: string;
  /**
   * Address line 1
   *
   */
  address1: string;
  /**
   * Address line 2
   *
   */
  address2?: string | null;
  /**
   * City
   *
   */
  city: string;
  /**
   * Postal code
   *
   */
  postalCode?: string | null;
  /**
   * Country name
   *
   */
  country: string;
  customData?: CustomDataType | null;
}
/**
 * This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
 */
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
/**
 * Element providing more information about the status.
 *
 */
export interface StatusInfoType {
  /**
   * A predefined code for the reason why the status is returned in this response. The string is case-insensitive.
   *
   */
  reasonCode: string;
  /**
   * Additional text to provide detailed information.
   *
   */
  additionalInfo?: string | null;
  customData?: CustomDataType | null;
}
