/**
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright 2023 S44, LLC
 */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { ConnectorStatusEnumType } from "../enums";
import { OcppRequest } from "../../..";

export interface StatusNotificationRequest extends OcppRequest {
  customData?: CustomDataType;
  /**
   * The time for which the status is reported. If absent time of receipt of the message will be assumed.
   *
   */
  timestamp: string;
  connectorStatus: ConnectorStatusEnumType;
  /**
   * The id of the EVSE to which the connector belongs for which the the status is reported.
   *
   */
  evseId: number;
  /**
   * The id of the connector within the EVSE for which the status is reported.
   *
   */
  connectorId: number;
}
/**
 * This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
 */
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}


