table:
  name: MeterValues
  schema: public
object_relationships:
  - name: Transaction
    using:
      foreign_key_constraint_on: transactionDatabaseId
  - name: TransactionEvent
    using:
      foreign_key_constraint_on: transactionEventId
