// SPDX-FileCopyrightText: 2025 Contributors to the CitrineOS Project
//
// SPDX-License-Identifier: Apache-2.0

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { FirmwareStatusNotificationRequestStatus } from '@ocpp/model/1.6/enums/index.js';
import type { OcppRequest } from '@ocpp/internal-types.js';

export interface FirmwareStatusNotificationRequest extends OcppRequest {
  status: FirmwareStatusNotificationRequestStatus;
}
