name: Linter

on:
  pull_request:

concurrency:
  # Rerun check when the PR is updated, https://stackoverflow.com/a/72408109
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-22.04 # todo: to prevent needing to run npm i we can have our own image where everything is installed
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run lint
