name: Linter

on:
  pull_request:

concurrency:
  # Rerun check when the PR is updated, https://stackoverflow.com/a/72408109
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-22.04 # todo: to prevent needing to run npm i we can have our own image where everything is installed
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run lint
